# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.CharField(default=267264, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='C', max_length=1),
            preserve_default=False,
        ),
    ]
