# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
