# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_school_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='students.Teacher'),
        ),
    ]
